### ISSUE TITLE
Builds and installs, but non-functional

### ISSUE THREAD

**Issue by jsquyres** [heqian/On11#1]
Greetings, and thanks for On11!

I'm trying to fork this project and build it myself, but am having a few problems.  After adding my own uuid:
1. It looks like some of the resources(e.g., graphics) are missing.  Are they supposed to be under resources/images?
2. When I build the app and install it on my Pebble, I get a blank screen.

I did have to run "pebble convert-project" to update the appinfo and wscript to be the latest API version; perhaps it's not compatible...?

Or is the code here on github just the core algorithms, and not meant to be the full-fledged On11 app, perchance?

**Comment by heqian** [comment]
Hi Jeff,

This repository contains the core functions you need to build an activity tracking app on Pebble. I didn't put any UI stuff here because I encourage developer friends to design more creative interfaces than mine, not just to customize On11.

Since the colorful Pebble Time is coming, I'm also considering completely re-designing On11's UI. I sincerely recommend you to take a look of Pebble's UI guide here: https://developer.getpebble.com/guides/pebble-apps/display-animations/ . It will help you implement UI elements on Pebble. :+1:

**Comment by jsquyres** [comment]
Got it; thank you!
